name: Deploy Laravel Components (Remote)
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Remote) por SSH por componentes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          debug: true
          script: |
            set -e
            cd /var/www/laravel
            git pull
            composer install --no-dev --optimize-autoloader
            php artisan optimize:clear
            php artisan migrate --force
            php artisan db:seed --class=UserSeeder --force
            php artisan db:seed --class=PostTypeSeeder --force
            php artisan db:seed --class=PostSeeder --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link || true
            sudo systemctl reload php8.3-fpm
            sudo systemctl reload nginx